name: tiktok_clone
description: "TikTok clone."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  # icons
  cupertino_icons: ^1.0.8

  # state management
  get: ^4.6.6

  # firebase core
  firebase_core: ^3.3.0

  # auth
  firebase_auth: ^5.1.4

  # database
  firebase_storage: ^12.1.3

  # file storage
  cloud_firestore: ^5.2.1

  # pick images from gallery
  image_picker: ^1.1.2

  # video player
  video_player: ^2.9.1

  # video compressor
  video_compress: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
