// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaaWr9PAhQ1SmUhVtJ5WACaf1xmH0PzQ4',
    appId: '1:165205711712:web:915f9450d110f0bbbedc05',
    messagingSenderId: '165205711712',
    projectId: 'tiktok-clone-15e76',
    authDomain: 'tiktok-clone-15e76.firebaseapp.com',
    storageBucket: 'tiktok-clone-15e76.appspot.com',
    measurementId: 'G-K6W07H5J79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaeOy7q-TZACOEihPBg9myxUS4J9gynUE',
    appId: '1:165205711712:android:fccdcda0e7f00796bedc05',
    messagingSenderId: '165205711712',
    projectId: 'tiktok-clone-15e76',
    storageBucket: 'tiktok-clone-15e76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6xDVX04EeCr-WVJCv21cKvpQEmzig3NQ',
    appId: '1:165205711712:ios:afb7d08192ccc770bedc05',
    messagingSenderId: '165205711712',
    projectId: 'tiktok-clone-15e76',
    storageBucket: 'tiktok-clone-15e76.appspot.com',
    iosBundleId: 'com.bilol.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6xDVX04EeCr-WVJCv21cKvpQEmzig3NQ',
    appId: '1:165205711712:ios:afb7d08192ccc770bedc05',
    messagingSenderId: '165205711712',
    projectId: 'tiktok-clone-15e76',
    storageBucket: 'tiktok-clone-15e76.appspot.com',
    iosBundleId: 'com.bilol.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaaWr9PAhQ1SmUhVtJ5WACaf1xmH0PzQ4',
    appId: '1:165205711712:web:9695254df2587c5ebedc05',
    messagingSenderId: '165205711712',
    projectId: 'tiktok-clone-15e76',
    authDomain: 'tiktok-clone-15e76.firebaseapp.com',
    storageBucket: 'tiktok-clone-15e76.appspot.com',
    measurementId: 'G-45TEQKW0Y8',
  );
}
